doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        # for fixtures via console BAD hack
        # url: '%env(resolve:DATABASE_URL_DOCTRINE)%'
        # url: 'postgresql://symfony:changeme@127.0.0.1:5432/alpha5?serverVersion=13&charset=utf8'
        url: 'postgresql://symfony:changeme@postgres_container:5432/alpha5?serverVersion=13&charset=utf8'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
