version: "3.5"

services:

  traefik69:
    image: "traefik:v2.5"
    container_name: "traefik69_c"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - net5

  symapi:
    build:
      context: .
    container_name: "symapi_c"
    volumes:
      - .:/var/www/html
    environment:
      - "PHP_ENABLE_XDEBUG=1"
      - "XDEBUG_CONFIG=idekey=PHPSTORM client_host=host.docker.internal xdebug.remote_port=9003 xdebug.discover_client_host=0 xdebug.start_with_request=yes xdebug.mode=develop,debug"
      - "XDEBUG_MODE=develop,debug"
      - "APACHE_DOCUMENT_ROOT=${DOCUMENT_ROOT}"
      - "PHP_IDE_CONFIG=serverName=symapi.localhost"
    ports:
      - "8084:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symapi.rule=Host(`symapi.localhost`)"
      - "traefik.http.routers.symapi.entrypoints=web"
    env_file:
      - .env
    networks:
      - net5

  postgressy:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-alpha5}" # user AND database to be created?
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
      PGDATA: /data/postgres
      # PGDATA: /var/lib/postgresql/data
      # PGDATA: /var/lib/postgresql/data
    volumes:
      # - _dbdata_pg:/var/lib/postgresql/data
      # - ./_dbdata_pg:/data/postgres
      - ./_dbdata5:/data/postgres 777
    env_file:
      - .env
    ports:
      - "5432:5432"
    # command: 'chmod 777 -R /var/lib/postgresql/data'
    # command: 'sudo chmod 700 -R /var/lib/postgresql/data'
    # command: 'chmod 700 -R /var/lib/postgresql/data'
    networks:
      - net5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - _pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgaalpha5.rule=Host(`pgaalpha5.localhost`)"
      - "traefik.http.routers.pgaalpha5.entrypoints=web"
    env_file:
      - .env
    networks:
      - net5

networks:
  net5:

volumes:
  _pgadmin:
  ###> doctrine/doctrine-bundle ###
  # _dbdata_pg:
  _dbdata5:
  ###< doctrine/doctrine-bundle ###
