###
GET {{host}}

###
GET symapi.localhost

###
GET 127.0.0.1:8084

###
GET {{host}}/letters

###
GET {{host}}/words

###
GET {{host}}/words/abcdefghi

###
GET {{host}}/words/abd

###
GET {{host}}/words/a-b-d

###
GET {{host}}/words/abcde/5

###
GET {{host}}/words/ae-b-r

###
GET {{host}}/words/ae-b-r/5


